apt_source: http://ports.ubuntu.com/ubuntu-ports
sshd_port: 3939
# written in sshd_config, so not boolean value.
sshd_passauth: "yes"

home_contents_dir_in_host: /mnt/g/マイドライブ/Ubuntu/home
home_path: "/home/{{ ansible_user }}"
home_bin_path: "{{ home_path }}/bin"
nanobackup_path: "{{ home_path }}/.nanobackup"
caddy_lego_url: https://caddyserver.com/api/download?os=linux&arch=arm64&p=github.com%2Fcaddy-dns%2Flego-deprecated
led_duration_on: 500
led_duration_off: 3500
# elecom32
usbdrive_path: /mnt/usb1
usbdrive_uuid: 90f32f5c-15f1-4766-89fb-760a2c18daf4

# Used when docker installation
docker_root: "{{ usbdrive_path }}/var/lib/docker"
docker_base_dir: "{{ home_path }}/docker"
pihole_web_port: 8100
nodered_web_port: 1880
n8n_web_port: 5678
portainer_api_port: 8000
portainer_web_port: 9443
